Feature/88
NaokiGoto123/attendmanager pull request #90
Opened 2020-07-01 17:41 UTC by NaokiGoto123

close #88 
ユーザーが変更可能なIDを持つように実装し、イベントやグループの削除という重い処理をcloud functionsに任せるようにした。
確認お願いします！

2020-07-01 21:54 UTC, dninomiya requested changes

2020-07-01 21:54 UTC, dninomiya commented on functions/src/delete.function.ts
> +    });
これでドキュメント配下全滅するので上でeventとか個別に消す必要ないと思います。（念のため上全部消して動作チェックはして欲しいですが）

2020-07-01 21:54 UTC, dninomiya commented on functions/src/delete.function.ts
> +    });
これでイベントID配下全滅するのでほかいらないかと

2020-07-01 21:54 UTC, dninomiya commented on functions/src/interfaces/event.ts
> +  // attendingMemberIds: string[]; // 参加中の人達 // サブコレ
よくわからないコメントアウトは残さない。理由があるならTODO：などでのちほどどう対処すべきか明記して残す

2020-07-01 21:54 UTC, dninomiya commented on functions/src/interfaces/event.ts
> +  private: boolean;
同じく

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/account/account/account.component.ts
> +                this.showAttendedEvents = user.showAttendedEvents;
userから参照できるのでプロパティ単位で保持させる必要ない

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/account/account/account.component.ts
> +                ];
このタイミングで定義する必要あります？userの結果関係なさそうですが

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/account/account/account.component.ts
> +              this.showAttendedEvents = user.showAttendedEvents;
認証サービスにgetUserがあるのは違和感。認証サービスはログインしている自分自身を管理するサービスであり、特定のユーザーを引っ張るような機能はuserServiceなどに持たせるのが自然。あとuserから全部引っ張れるのでuserの各プロパティ代入する必要なし

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/account/invited-events/invited-events.component.ts
> +        });
??

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/account/invited-groups/invited-groups.component.ts
> +        });
??　ただsubscribeさせたいだけな状態は違和感。serviceに過度に値を保持させるのではなく、serviceが必要箇所に結果をObservableなどで返却する実装が自然

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/events/events/events.component.html
> +      <h1 routerLink="/create-event">Create event</h1>
h1おかしい

2020-07-01 21:54 UTC, dninomiya commented on src/app/shell/events/events/events.component.html
> +      <img class="no-event-image" src="/assets/images/schedule1.svg" />
alt

2020-07-02 04:54 UTC, NaokiGoto123 commented on functions/src/interfaces/event.ts
> +  // attendingMemberIds: string[]; // 参加中の人達 // サブコレ
対処しました。

2020-07-02 04:54 UTC, NaokiGoto123 commented on functions/src/interfaces/event.ts
> +  private: boolean;
対処しました。

2020-07-02 05:27 UTC, NaokiGoto123 commented on src/app/shell/account/account/account.component.ts
> +              this.showAttendedEvents = user.showAttendedEvents;
userService作成しました！

2020-07-02 05:29 UTC, NaokiGoto123 commented on src/app/shell/account/account/account.component.ts
> +                ];
そこはもし自分のページに飛んできたらという処理です！

2020-07-02 05:31 UTC, NaokiGoto123 commented on src/app/shell/account/account/account.component.ts
> +                this.showAttendedEvents = user.showAttendedEvents;
component.html内でuser.searchIdなどとやろうとすると、searchId of undefinedというエラーが出てきてしまうので仕方なく個別に定義しているという感じです。

2020-07-02 05:48 UTC, deerboy commented on src/app/shell/account/account/account.component.ts
> +                ];
routeLinks使ってるコンポーネントはたくさんありますか？一つしかないならコンポーネント側で管理する方が自然です。

2020-07-02 05:52 UTC, NaokiGoto123 commented on functions/src/delete.function.ts
> +    });
groupsとeventsは別々に管理しているので、groups/eventIdsから参照する形でgroupsとeventsを紐付けています。

2020-07-02 05:55 UTC, NaokiGoto123 commented on functions/src/delete.function.ts
> +    });
groups/eventIdsにはeventIdsしかないので、データを取って来る時は参照する形でeventsから持って来る形になっています。ですのでgroup配下のeventIdsを消しても、events配下のevent達を消す必要があります。

2020-07-02 05:58 UTC, NaokiGoto123 commented on src/app/shell/account/invited-events/invited-events.component.ts
> +        });
Algolia実装した後にここの作業をするので、今はまだ必要なデータを取ってきているだけの状態です。

2020-07-02 06:00 UTC, NaokiGoto123 commented on src/app/shell/events/events/events.component.html
> +      <h1 routerLink="/create-event">Create event</h1>
```html
<h1>You do not have any events.
<span routerLink="/search/events">Search for events</span>
<span>or</span>
<span routerLink="/create-event">Create event</span>
</h1>
```
ということでしょうか？

2020-07-02 06:30 UTC, NaokiGoto123 commented on src/app/shell/events/events/events.component.html
> +      <img class="no-event-image" src="/assets/images/schedule1.svg" />
変更済

2020-07-02 06:31 UTC, NaokiGoto123 commented on src/app/shell/account/invited-groups/invited-groups.component.ts
> +        });
今はsubscribeしているだけですが、algolia実装が終わってからここの作業しようと予定してます。

2020-07-02 06:51 UTC, deerboy commented on src/app/shell/account/account/account.component.ts
> +                this.showAttendedEvents = user.showAttendedEvents;
user?xxx

とすればよいです。この持たせ方は無駄が多いので避けたい

2020-07-02 06:51 UTC, deerboy commented on src/app/shell/account/invited-events/invited-events.component.ts
> +        });
TODOコメント入れておきましょう👌

2020-07-02 06:53 UTC, deerboy commented on src/app/shell/events/events/events.component.html
> +      <h1 routerLink="/create-event">Create event</h1>
h1 つかいどころ　とかでぐぐりましょう。あるいは、MDNでh1を如何いうときに使うべきか見てみる。

そのページのタイトルを表すので、たくさんあったり操作系のてきすとを囲むのはおかしいです

2020-07-02 06:59 UTC, NaokiGoto123 commented on src/app/shell/account/account/account.component.ts
> +                this.showAttendedEvents = user.showAttendedEvents;
無駄がだいぶ減りました、ありがとうございます！

2020-07-02 07:30 UTC, NaokiGoto123 commented on src/app/shell/events/events/events.component.html
> +      <h1 routerLink="/create-event">Create event</h1>
変更しました！

2020-07-02 12:10 UTC, NaokiGoto123 commented
ご確認のほどお願いします！

2020-07-02 20:54 UTC, merged